# Generated by Django 3.2 on 2022-12-16 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('Letra', models.CharField(help_text='Introducir la Letra de la Clase', max_length=2, primary_key=True, serialize=False, unique=True)),
                ('Profesor', models.CharField(help_text='Introduce el nombre del profesor asignado', max_length=100)),
                ('FotoProfesor', models.ImageField(upload_to='static/imagenes/profesores/')),
                ('Password', models.CharField(max_length=100)),
                ('FotoClase', models.ImageField(null=True, upload_to='static/imagenes/clases/')),
                ('Check', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Imagen', models.ImageField(upload_to='static/imagenes/estudiantes/')),
                ('Password', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_ini', models.DateField()),
                ('Fecha_fin', models.DateField()),
                ('Documento', models.FileField(upload_to='static/imagenes/menusAnteriores/')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imagen', models.ImageField(upload_to='static/imagenes/imagen_password')),
                ('Nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('Tipo', models.CharField(help_text='Introducir el tipo de menu', max_length=100, primary_key=True, serialize=False)),
                ('Imagen', models.ImageField(upload_to='static/imagenes/menus/')),
            ],
        ),
        migrations.CreateModel(
            name='Numero',
            fields=[
                ('Numero', models.IntegerField(primary_key=True, serialize=False)),
                ('Imagen', models.ImageField(upload_to='static/imagenes/numeros/')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('complete', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solicita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField()),
                ('Clase_asociada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoApp.clase')),
                ('TipoMenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoApp.menu')),
            ],
        ),
    ]
