# Generated by Django 3.2.6 on 2022-11-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='FotoProfesor',
            field=models.ImageField(upload_to='static/profesores/'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='Imagen',
            field=models.ImageField(upload_to='static/estudiantes/'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='Documento',
            field=models.FileField(upload_to='static/menusAnteriores/'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='Imagen',
            field=models.ImageField(upload_to='static/menus/'),
        ),
        migrations.AlterField(
            model_name='numero',
            name='Imagen',
            field=models.ImageField(upload_to='static/numeros/'),
        ),
    ]
