# Generated by Django 4.1.3 on 2022-11-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0002_alter_clase_fotoprofesor_alter_estudiante_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='Password',
            field=models.CharField(default='123', max_length=100),
        ),
    ]
