# Generated by Django 4.1.2 on 2022-11-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0002_clase_estudiante_historico_menu_numero_solicita'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='Check',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='Imagen',
            field=models.ImageField(upload_to='static/imagenes/estudiantes'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='Documento',
            field=models.FileField(upload_to='static/docs/historico'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='Imagen',
            field=models.ImageField(upload_to='static/imagenes/menus'),
        ),
        migrations.AlterField(
            model_name='numero',
            name='Imagen',
            field=models.ImageField(upload_to='static/imagenes/manos'),
        ),
    ]
