# Generated by Django 4.1.3 on 2022-11-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0003_clase_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='Password',
            field=models.CharField(max_length=100),
        ),
    ]
