# Generated by Django 4.1.3 on 2022-11-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0005_imagenpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='Password',
            field=models.CharField(default='gato gato gato', max_length=1000),
        ),
    ]
