# Generated by Django 3.2 on 2022-12-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0007_alter_estudiante_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='FotoClase',
            field=models.ImageField(null=True, upload_to='static/imagenes/clases/'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='FotoProfesor',
            field=models.ImageField(upload_to='static/imagenes/profesores/'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='Imagen',
            field=models.ImageField(upload_to='static/imagenes/estudiantes/'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='Documento',
            field=models.FileField(upload_to='static/imagenes/menusAnteriores/'),
        ),
        migrations.AlterField(
            model_name='imagenpassword',
            name='Imagen',
            field=models.ImageField(upload_to='static/imagenes/imagen_password'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='Imagen',
            field=models.ImageField(upload_to='static/imagenes/menus/'),
        ),
        migrations.AlterField(
            model_name='numero',
            name='Imagen',
            field=models.ImageField(upload_to='static/imagenes/numeros/'),
        ),
    ]
