# Generated by Django 3.2 on 2022-12-16 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0008_auto_20221216_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=250)),
                ('Imagen', models.ImageField(upload_to='static/imagenes/pasos')),
            ],
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoApp.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('Id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=50)),
                ('FechaIni', models.DateField()),
                ('FechaFin', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AddField(
            model_name='pool',
            name='Tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoApp.tarea'),
        ),
        migrations.AddField(
            model_name='paso',
            name='Tarea_asociada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoApp.tarea'),
        ),
    ]
