# Generated by Django 3.2.6 on 2022-12-21 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0009_auto_20221216_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='FechaFin',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='FechaIni',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='ModoImagen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pool',
            name='Check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pool',
            name='FechaFin',
            field=models.DateField(default=datetime.date(2022, 12, 23)),
        ),
        migrations.AddField(
            model_name='pool',
            name='FechaIni',
            field=models.DateField(default=datetime.date(2022, 12, 21)),
        ),
    ]
