# Generated by Django 4.1.3 on 2022-12-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0010_auto_20221221_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='Tipo',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
