# Generated by Django 3.2 on 2022-12-21 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0011_tarea_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='paso',
            name='Orden',
            field=models.IntegerField(default=0),
        ),
    ]
