# Generated by Django 4.1.3 on 2022-12-21 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0011_tarea_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='Tipo',
            field=models.CharField(help_text='C => Comedor | A => Almacen | Nada => Tarea normal', max_length=1, null=True),
        ),
    ]
