# Generated by Django 3.2 on 2022-12-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0012_paso_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='Tipo',
            field=models.CharField(help_text='C => Comedor | A => Almacen | Nada => Tarea normal', max_length=1, null=True),
        ),
    ]
