# Generated by Django 3.2 on 2022-12-22 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0012_paso_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='FechaFin',
            field=models.DateField(default=datetime.date(2022, 12, 24)),
        ),
        migrations.AlterField(
            model_name='pool',
            name='FechaIni',
            field=models.DateField(default=datetime.date(2022, 12, 22)),
        ),
    ]
