# Generated by Django 4.1.2 on 2022-12-22 01:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0013_auto_20221222_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='FechaIni',
            field=models.DateTimeField(default=datetime.date(2022, 12, 22)),
        ),
    ]
