# Generated by Django 4.1.2 on 2022-12-22 01:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0014_alter_pool_fechaini'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='FechaFin',
            field=models.DateTimeField(default=datetime.date(2022, 12, 24)),
        ),
    ]
