# Generated by Django 4.1.2 on 2022-12-22 02:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0015_alter_pool_fechafin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='FechaIni',
            field=models.DateTimeField(default=datetime.date(2022, 12, 22), verbose_name=['%m/%d/%Y %H:%M']),
        ),
    ]
